#!/usr/bin/env python3
"""Run a SkyPilot task yaml on a plain SSH host (e.g. a RunPod pod) instead of the cluster.

The yaml's `envs` (defaults, overridden by --env KEY=VAL), `file_mounts` (local files scp'd
to their destination paths), `setup` and `run` sections are executed verbatim on the host
under nohup, with local directories standing in for the cluster mounts:

    /mnt/raid0            -> node-local scratch (created on the pod's local disk)
    /checkpoints/<user>   -> results volume (created locally; results also go to W&B)
    K8S_NODE              -> "runpod"
    sudo                  -> a pass-through shim when the container has none (root)
    secrets               -> WANDB_API_KEY / GIT_TOKEN must already be in the pod's environment

Usage:
    run_yaml_on_pod.py --host root@1.2.3.4 --port 22154 --key ~/.ssh/id_ed25519 \
        --yaml scripts/sky/unigamma/tworoom_g98_rescue.yaml --name rlp-tw-uniJ-pod \
        --env ENVNAME=tworoom --env BASE=lejepa ...            # then:
    run_yaml_on_pod.py ... --name rlp-tw-uniJ-pod --status     # tail logs / exit code
Nothing secret is written into the job files: the env file references $WANDB_API_KEY and
$GIT_TOKEN from the pod's own environment.
"""
import argparse, os, shlex, subprocess, sys, tempfile
import yaml

ap = argparse.ArgumentParser()
ap.add_argument("--host", required=True); ap.add_argument("--port", type=int, default=22)
ap.add_argument("--key", default=os.path.expanduser("~/.ssh/id_ed25519"))
ap.add_argument("--yaml", required=True); ap.add_argument("--name", required=True)
ap.add_argument("--env", action="append", default=[], help="KEY=VAL override (repeatable)")
ap.add_argument("--jobroot", default="/root/podjobs", help="on RunPod /workspace is a slow network FS; keep jobs on the local container disk")
ap.add_argument("--scratch", default="/scratch/raid0", help="LOCAL-disk dir that stands in for /mnt/raid0 (never a network FS)")
ap.add_argument("--status", action="store_true", help="only show the job's status/log tail")
ap.add_argument("--stop", action="store_true", help="kill the job's process group")
ap.add_argument("--no-start", action="store_true", help="ship the job files only; start later (e.g. from a sequential chain on the pod)")
ap.add_argument("--dry", action="store_true", help="prepare files locally, print, do not ship")
ap.add_argument("--home", default="", help="run with this HOME (default: the login HOME). Concurrent jobs on one pod MUST use separate homes: the yamls symlink ~/gh ~/gm ... per job")
ap.add_argument("--workdir", default="", help="ship this git working tree (tracked + untracked-not-ignored files, minus assets/ docs/) to $HOME/sky_workdir on the pod, like SkyPilot workdir: .")
ap.add_argument("--pre", default="", help="shell snippet run on the pod BEFORE the yaml setup (e.g. pin torch to the cluster image)")
ap.add_argument("--post-setup", default="", help="shell snippet appended to the yaml's setup (e.g. swap in a torch build for the pod's GPU arch)")
ap.add_argument("--with-assets", action="store_true", help="also ship assets/core/world_model (551 MB): the l2o/dmpo campaigns read the base world models from there, unlike the tworoom/cube yamls which fetch their own")
a = ap.parse_args()

SSH = ["ssh", "-o", "StrictHostKeyChecking=accept-new", "-o", "ServerAliveInterval=30", "-p", str(a.port), "-i", a.key, a.host]
SCP = ["scp", "-o", "StrictHostKeyChecking=accept-new", "-P", str(a.port), "-i", a.key]
def ssh(cmd, check=True, capture=False):
    r = subprocess.run(SSH + [cmd], check=check, text=True, capture_output=capture)
    return r.stdout if capture else None

jobdir = f"{a.jobroot}/{a.name}"
if a.status:
    print(ssh(f"cd {jobdir} 2>/dev/null && echo '== exit:' && cat exit_code 2>/dev/null || echo running; "
              f"echo '== setup.log (tail)'; tail -5 setup.log 2>/dev/null; echo '== run.log (tail)'; tail -25 run.log 2>/dev/null; "
              f"echo '== pgid'; cat pgid 2>/dev/null; pgrep -g $(cat pgid 2>/dev/null || echo 0) | wc -l", check=False, capture=True))
    sys.exit(0)
if a.stop:
    ssh(f"cd {jobdir} && kill -TERM -- -$(cat pgid) && echo stopped", check=False); sys.exit(0)

task = yaml.safe_load(open(a.yaml))
envs = {k: ("" if v is None else str(v)) for k, v in (task.get("envs") or {}).items()}
for kv in a.env:
    k, _, v = kv.partition("="); envs[k] = v
for req in ("ENVNAME", "BASE", "EXPERIMENT_TAG"):
    if not envs.get(req): sys.exit(f"missing --env {req}")
envs.setdefault("PANTHEON_USER", "armin@pantheon.inc")
envs["K8S_NODE"] = "runpod"

env_lines = ["#!/usr/bin/env bash", "# generated by run_yaml_on_pod.py -- secrets come from the pod environment",
             "export WANDB_API_KEY=\"${WANDB_API_KEY:?WANDB_API_KEY not set on the pod}\"",
             "export GIT_TOKEN=\"${GIT_TOKEN:?GIT_TOKEN not set on the pod}\""]
env_lines += [f"export {k}={shlex.quote(v)}" for k, v in envs.items()]
launcher = f"""#!/usr/bin/env bash
# stand-ins for the cluster mounts
mkdir -p {a.scratch} && ([ -e /mnt/raid0 ] || (mkdir -p /mnt && ln -s {a.scratch} /mnt/raid0))
mkdir -p "/checkpoints/{envs['PANTHEON_USER']}" /tmp/codex-overlays
command -v sudo >/dev/null 2>&1 || printf '#!/bin/sh\\nexec "$@"\\n' > /usr/local/bin/sudo && chmod +x /usr/local/bin/sudo
# as root, GNU tar tries to restore archive ownership and fails on the pod overlay FS
export TAR_OPTIONS=--no-same-owner
# 16 trainers + parallel evals each spawning #cores torch/OMP threads saturate the CPUs (load 570 on 208
# cores observed); cap per-process threads
export OMP_NUM_THREADS=${{OMP_NUM_THREADS:-8}} MKL_NUM_THREADS=${{MKL_NUM_THREADS:-8}}
{("export HOME=" + a.home + " && mkdir -p " + a.home) if a.home else "true"}
# a constraints file written by --pre pins packages (torch) across every later pip install
[ -f {jobdir}/constraints.txt ] && export PIP_CONSTRAINT={jobdir}/constraints.txt
# the yaml symlinks ~/gh ~/gm ~/gc ~/gd ~/gl ~/ga into the cache/scratch dirs and refuses to replace
# an existing path; on a reused pod the previous run left those symlinks behind -- drop symlinks only
for d in gh gm gc gd gl ga; do [ -L "$HOME/$d" ] && rm -f "$HOME/$d"; done
cd {jobdir}
# RunPod injects pod env vars (incl. Secrets) into pid 1 / /etc/rp_environment, not into sshd sessions
[ -f /etc/rp_environment ] && set -a && . /etc/rp_environment && set +a
# the Secrets themselves live only in pid 1's environment: pull the two we need from there
for v in WANDB_API_KEY GIT_TOKEN; do [ -n "${{!v:-}}" ] || export "$v=$(xargs -0 -n1 printf '%s\\n' < /proc/1/environ | sed -n "s/^$v=//p" | head -1)"; done
source ./env.sh
rm -f exit_code
# a previous (killed) run of this tag leaves mkdir slot locks behind => the yaml would run at half concurrency
rm -rf /mnt/raid0/rlp-runs/{envs['EXPERIMENT_TAG']}/shard-*/gl/slots 2>/dev/null
echo "[pod-runner] pre $(date -u +%FT%TZ)" > run.log
bash ./pre.sh > pre.log 2>&1; rc=$?
if [ $rc -ne 0 ]; then echo "pre failed rc=$rc" | tee -a run.log; echo $rc > exit_code; exit $rc; fi
echo "[pod-runner] setup $(date -u +%FT%TZ)" >> run.log
bash ./setup.sh > setup.log 2>&1; rc=$?
if [ $rc -ne 0 ]; then echo "setup failed rc=$rc" | tee -a run.log; echo $rc > exit_code; exit $rc; fi
echo "[pod-runner] run $(date -u +%FT%TZ)" >> run.log
bash ./run.sh >> run.log 2>&1; rc=$?
echo $rc > exit_code; echo "[pod-runner] done rc=$rc $(date -u +%FT%TZ)" >> run.log
"""
with tempfile.TemporaryDirectory() as td:
    open(f"{td}/env.sh", "w").write("\n".join(env_lines) + "\n")
    open(f"{td}/setup.sh", "w").write(task["setup"] + ("\n" + a.post_setup + "\n" if a.post_setup else ""))
    open(f"{td}/run.sh", "w").write(task["run"])
    open(f"{td}/launch.sh", "w").write(launcher)
    open(f"{td}/pre.sh", "w").write("#!/usr/bin/env bash\nset -euo pipefail\n" + (a.pre or "true") + "\n")
    if a.dry:
        print(open(f"{td}/env.sh").read()[:1500]); print("...\n[dry] files prepared; not shipped"); sys.exit(0)
    ssh(f"mkdir -p {jobdir} /tmp/codex-overlays /tmp && nvidia-smi -L | head -8")
    subprocess.run(SCP + [f"{td}/env.sh", f"{td}/setup.sh", f"{td}/run.sh", f"{td}/launch.sh", f"{td}/pre.sh", f"{a.host}:{jobdir}/"], check=True)
    yaml_dir = os.path.dirname(os.path.abspath(a.yaml))
    repo_root = subprocess.run(["git", "rev-parse", "--show-toplevel"], cwd=yaml_dir, text=True, capture_output=True).stdout.strip() or os.getcwd()
    for dest, src in (task.get("file_mounts") or {}).items():
        local = src if os.path.isabs(src) else os.path.join(repo_root, src)
        if not os.path.exists(local): sys.exit(f"file_mount source missing: {local}")
        ssh(f"mkdir -p {os.path.dirname(dest)}")
        subprocess.run(SCP + [local, f"{a.host}:{dest}"], check=True)
        print(f"[mount] {src} -> {dest}")
    # start detached in its own process group so --stop can kill the whole tree
    if a.workdir:
        # code-only snapshot of the working tree (yamls with `workdir: .` expect ~/sky_workdir); assets/ (world models)
        # and docs/ are excluded -- 600 MB of checkpoints the PushT stack fetches itself
        keep_assets = "" if a.with_assets else " | grep -v '^assets/'"
        files = subprocess.run(["bash", "-c", "cd " + a.workdir + " && { git ls-files; git ls-files --others --exclude-standard; }"
                               + keep_assets + " | grep -v '^docs/' | sort -u"],
                               text=True, capture_output=True, check=True).stdout
        lst = f"{td}/workdir_files.txt"; open(lst, "w").write(files)
        tarball = f"{td}/workdir.tar.gz"
        subprocess.run(["tar", "-czf", tarball, "-C", a.workdir, "-T", lst], check=True)
        home = a.home or "$HOME"
        ssh(f"mkdir -p {home}/sky_workdir")
        subprocess.run(SCP + [tarball, f"{a.host}:{jobdir}/workdir.tar.gz"], check=True)
        ssh(f"cd {home}/sky_workdir && tar --no-same-owner -xzf {jobdir}/workdir.tar.gz && echo '[workdir] ' $(find . -type f | wc -l) files in {home}/sky_workdir")
    if a.no_start:
        print(f"[pod-runner] {a.name} shipped to {a.host}:{jobdir} (not started)"); sys.exit(0)
    # record THIS job's process group (pgrep -f 'launch.sh' would find another job's launcher on a shared pod)
    ssh(f"cd {jobdir} && chmod +x launch.sh && (setsid nohup bash ./launch.sh >/dev/null 2>&1 < /dev/null & echo $! > pid); sleep 1; "
        f"cd {jobdir} && ps -o pgid= -p $(cat pid) | tr -d ' ' > pgid; echo started pid=$(cat pid) pgid=$(cat pgid)")
    print(f"[pod-runner] {a.name} started on {a.host}; logs: {jobdir}/{{setup,run}}.log ; status: --status")
