# @package core.world_model
name: prejepa
checkpoint: null
history_size: 3
num_predictions: 1
encoding:
  proprio: 41
  action: 10
backbone:
  name: dinov2_small
  is_video_encoder: false
  patch_size: 14
architecture:
  _target_: stable_worldmodel.wm.PreJEPA
  history_size: ${core.world_model.history_size}
  num_pred: ${core.world_model.num_predictions}
  interpolate_pos_encoding: true
  encoder:
    _target_: stable_worldmodel.wm.prejepa.module.create_backbone
    name: ${core.world_model.backbone.name}
  predictor:
    _target_: stable_worldmodel.wm.prejepa.module.CausalPredictor
    num_patches: 0  # derived from encoder and image size
    num_frames: ${core.world_model.history_size}
    dim: 0  # derived from encoder and configured modalities
    depth: 6
    heads: 16
    mlp_dim: 2048
    dim_head: 64
    dropout: 0.1
    emb_dropout: 0.0
