output_model_name: ogbench_cube_single_lewm
subdir: ogbench_cube_single_lewm_20260701T080809Z
num_workers: 12
train_split: 0.9
seed: 3072
img_size: 224
patch_size: 14
encoder_scale: tiny
embed_dim: 192
encoder_resnet9: false
train_value_function: false
projector_loss_weight: 0.001
dump_object: true
trainer:
  max_epochs: 1000
  devices: 1
  accelerator: gpu
  precision: bf16-mixed
  gradient_clip_val: 1.0
  max_steps: 100000
loader:
  batch_size: 256
  num_workers: 12
  drop_last: true
  persistent_workers: true
  prefetch_factor: 3
  pin_memory: true
  shuffle: true
optimizer:
  type: AdamW
  lr: 5.0e-05
  weight_decay: 0.001
  scheduler_interval: step
wm:
  history_size: 3
  num_preds: 1
model:
  _target_: stable_worldmodel.wm.lewm.LeWM
  encoder:
    _target_: stable_pretraining.backbone.utils.vit_hf
    size: ${encoder_scale}
    patch_size: ${patch_size}
    image_size: ${img_size}
    pretrained: false
    use_mask_token: false
  predictor:
    _target_: stable_worldmodel.wm.lewm.module.Predictor
    num_frames: ${wm.history_size}
    input_dim: ${embed_dim}
    hidden_dim: ${embed_dim}
    output_dim: ${embed_dim}
    depth: 6
    heads: 16
    mlp_dim: 2048
    dim_head: 64
    dropout: 0.1
    emb_dropout: 0.0
  action_encoder:
    _target_: stable_worldmodel.wm.lewm.module.Embedder
    input_dim: 25
    emb_dim: ${embed_dim}
  projector:
    _target_: stable_worldmodel.wm.lewm.module.MLP
    input_dim: ${embed_dim}
    output_dim: ${embed_dim}
    hidden_dim: 2048
    norm_fn:
      _target_: torch.nn.BatchNorm1d
      _partial_: true
  pred_proj:
    _target_: stable_worldmodel.wm.lewm.module.MLP
    input_dim: ${embed_dim}
    output_dim: ${embed_dim}
    hidden_dim: 2048
    norm_fn:
      _target_: torch.nn.BatchNorm1d
      _partial_: true
loss:
  sigreg:
    weight: 0.09
    kwargs:
      knots: 17
      num_proj: 1024
  reconstruction:
    weight: 0.0
  proprio:
    weight: 0.0
diagnostics:
  every_n_steps: 100
timed_eval:
  enabled: false
  interval_seconds: 3600
  run_at_start: true
  first_step: 1000
  num_clips: 2
  fps: 4
  max_val_batches: 128
  show_pred: true
checkpoint:
  epoch_interval: 0
  every_n_train_steps: 10000
n_gpus: 1
cpus_per_task: 8
cache_dir: null
wandb:
  enabled: true
  config:
    entity: yash21-dagade-duke-university
    project: pantheon-swm
    name: ogbench_cube_single_lewm_20260701T080809Z
    id: ogbench_cube_single_lewm_20260701T080809Z
    resume: allow
    log_model: false
    group: ogbench_cube_3gpu_20260701T080809Z
data:
  dataset:
    name: /workspace/datasets/ogbench_swm/visual_cube_single_play_v0.h5
    num_steps: ${eval:'${wm.num_preds} + ${wm.history_size}'}
    frameskip: 5
    keys_to_load:
    - pixels
    - action
    keys_to_cache:
    - action
