# @package core.solver
_target_: rlp.core.solver.HLIPSolver
batch_size: 1
num_samples: 300
var_scale: 1.0
n_steps: 0
topk: 30
ll_actor_path: ???
hl_actor_path: ???
hwm_path: null
hl: lip
ll: lip
hl_cutoff: -1.0
subgoal_index: 0
hl_horizon: 0
hl_samples: 1024
hl_iters: 8
hl_lam: 0.01
hl_amax: 3.0
hl_cost: terminal
ll_samples: 300
ll_iters: 30
ll_lam: 0.01
ll_amax: 3.5
subgoal_project: false
project_pool: null
subgoal_select: index
reach_target: 30.0
