# @package _global_
defaults:
  - /data: ogb_cube_lewm
  - /core/world_model: lewm
  - /logging: default
  - _self_
entrypoint:
  _target_: rlp.train.lewm._run
runtime:
  seed: 3072
  device: auto
train:
  initial_weights: null
  trainer:
    max_epochs: 100
    devices: auto
    accelerator: auto
    precision: bf16-mixed
    gradient_clip_val: 1.0
  optimizer:
    type: AdamW
    lr: 5e-5
    weight_decay: 1e-3
  loss:
    sigreg:
      weight: 0.09
      kwargs:
        knots: 17
        num_proj: 1024
output:
  model_name: lewm_cube
